name: Auto day template
on:
  workflow_dispatch:
  schedule:
  - cron: "30 6 * 12 *"
jobs:
  sync_day:
    name: Sync get the Day of Advent Of Code
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Get the new days and save it to git
        run: |
          nbDay=$(date +'%d')
          tmpPathInput=src/day${nbDay}/Day${nbDay}.txt
          tmpPathFile=src/day${nbDay}/Day${nbDay}.kt
          tmpPathInputTest=src/day${nbDay}/Day${nbDay}_test.kt
          mkdir -p src/day${nbDay}
          cp day_template.kt $tmpPathFile
          curl https://adventofcode.com/2022/day/${nbDay}/input>${tmpPathInput}
          cp day_inputs_test_template.txt $tmpPathInputTest
          git config --global user.email ${{ secrets.GH_EMAIL }}
          git config --global user.name ${{ secrets.GH_NAME }}
          git add $tmpPathInput 
          git add $tmpPathFile
          git add $tmpPathInputTest
          git commit -a -m "feat(Day${nbDay}): Add input" --author="apeinte"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


