on:
  workflow_dispatch:
  schedule:
  - cron: "30 6 * 12 *"
jobs:
  sync_day:
    name: Sync get the Day of Advent Of Code
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Check if last days is existing
        run: |
          echo "date::$(date +'%Y%m%d%H%M')"
          set nbDay=echo "date::$(date +'%d')"
          cat nbDay
          
      
  
